<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ReichTUM</title>
    <link rel="shortcut icon" href="../../static/images/favicon.png">
    <link rel="stylesheet" href="css/loginStyle.css">
</head>
<body>
    <div class="figurenwahl">
        <h1 class="text">Willkommen bei ReichTUM</h1>
        <div class="text">Wähle deine Spielfigur.</div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="fingerhut" class="container">
                <input type="radio" checked="checked" name="spielfigur"></input>
                <img class="image" src="/images/Fingerhut.png" alt="Fingerhut">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="schubkarre" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Schubkarre.png" alt="Schubkarre">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="schuh" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Schuh.png" alt="Schuh">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="hund" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Hund.png" alt="Hund">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="automobil" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Automobil.png" alt="Automobil">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="bügeleisen" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="./images/Bügeleisen.png" alt="Bügeleisen">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="zylinder" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Zylinder.png" alt="Zylinder">
                <span class="checkmark"></span>
            </label>
        </div>
        <div class="spielfigur col-lg-3 col-md-3 col-sm-6">
            <label id="schlachtschiff" class="container">
                <input type="radio" name="spielfigur"></input>
                <img class="image" src="/images/Schlachtschiff.png" alt="Schlachtschiff">
                <span class="checkmark"></span>
            </label>
        </div>
        <button class="btn">Los geht's!</button>
    </div>
</body>
</html>